site_name: hiromaru8's page

# テーマ
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# GitHub
repo_url: https://github.com/hiromaru8/Mypage
repo_name: Mypage


# ドキュメントの構成
nav:
  - Top page    : index.md
  - hardware    : Hardware/hardware.md
  - OS :
      - Linux : 
        - OS/Linux/Linux.md
        - LPIC    : OS/Linux/LPIC.md
  - Programing  : 
      - C/C++     : Programing/C_Cplusplus/C_Cplusplus.md
      - Python    : Programing/Python/python.md
  - FPGA        : 
      - FPGA/FPGA.md
      - BRAM      : FPGA/BRAM/bram.md
      - ZYNQ      : FPGA/Zynq/Zynq.md
  - プロジェクト管理 :
      - Git       : mngPrg/git/git.md
  - ドキュメント: 
      - markdown  : document/markdown/markdown.md
  - Device      : 
      - Rasberry Pi : divice\RaspberryPi\RaspberryPi.md
  - TCP/IP      :
      - Wireshark : TCPIP\Wireshark\wireshark.md
  - 設計書  :
    - 基本設計書  : design_doc/1_base_design_doc_1.md
    - 詳細設計書  : design_doc/2_detail_design_doc_1.md
    - sample :
      - 基本設計 : design_doc\sample\1_base_sample.md
      - 詳細設計 : design_doc\sample\2_detaile_sample.md
  - モデルベースデザイン :
      - MBD : mbd/index.md
  - Memo :
    - memo : memo/index.md
